DeviceProcessEvents
| where TimeGenerated between (datetime(2026-07-10) .. datetime(2026-07-12 23:59:59))
| where AccountName in~ ("Administrator", "Backdoor")
| where ProcessCommandLine has_any (
    "whoami",
    "net user",
    "tasklist",
    "ipconfig",
    "certutil",
    "localgroup administrators",
    "urlcache"
)
| project
    TimeGenerated,
    DeviceName,
    AccountName,
    FileName,
    ProcessCommandLine,
    InitiatingProcessFileName,
    InitiatingProcessCommandLine
| order by TimeGenerated desc
