let SuspiciousProcesses = DeviceProcessEvents
| where TimeGenerated >= ago(24h)
| where FileName =~ "certutil.exe"
| where InitiatingProcessFileName =~ "Powershell.exe"
| where ProcessCommandLine has_any ("urlcache","encode","decode","split")
| project
    DeviceName,
    AccountName,
    ProcessCommandLine,
    ProcessTime = TimeGenerated,
    ProcessId;
let SuspiciousNetwork = DeviceNetworkEvents
| where TimeGenerated >= ago(24h)
| where InitiatingProcessFileName =~ "Powershell.exe"
| where RemoteIPType != "Private"
| project
    DeviceName,
    RemoteUrl,
    RemoteIP,
    RemotePort,
    NetworkTime = TimeGenerated,
    InitiatingProcessId;
SuspiciousProcesses
| join kind=leftouter SuspiciousNetwork
    on DeviceName, $left.ProcessId == $right.InitiatingProcessId
| order by ProcessTime desc
